# frozen_string_literal: true

# This file was generated by bin/update-formulae.
class Cerebro < Formula
  desc "Manage and secure Linux servers over Tailscale SSH"
  homepage "https://github.com/almeidx/cerebro"
  version "0.1.1-alpha.2"
  license "Apache-2.0"

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/almeidx/cerebro/releases/download/v0.1.1-alpha.2/cerebro-0.1.1-alpha.2-x86_64-unknown-linux-musl.tar.gz"
      sha256 "8a928334ebf23d435da08ec09c63874a1e310a90e0fdf4d6d96be03e2c00b04f"
    end

    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/almeidx/cerebro/releases/download/v0.1.1-alpha.2/cerebro-0.1.1-alpha.2-aarch64-unknown-linux-musl.tar.gz"
      sha256 "2d81867717f97738d951a41176fc53e3f5587b9f23cdc70d132f0d29038b19aa"
    end
  end

  def install
    bin.install "cerebro"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cerebro --version")
  end
end
