# frozen_string_literal: true

# This file was generated by bin/update-formulae.
class Uatu < Formula
  desc "Observe cron jobs without replacing cron"
  homepage "https://github.com/almeidx/uatu"
  version "0.1.1-alpha.3"
  license "Apache-2.0"

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/almeidx/uatu/releases/download/v0.1.1-alpha.3/uatu-0.1.1-alpha.3-x86_64-unknown-linux-musl.tar.gz"
      sha256 "5c896104b33ac0ac19087b0fdedfe5390bfc11081be80b0a5e57829044cc1910"
    end

    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/almeidx/uatu/releases/download/v0.1.1-alpha.3/uatu-0.1.1-alpha.3-aarch64-unknown-linux-musl.tar.gz"
      sha256 "97559184108861a83f84c3ecb345ba188c0510680a93a90f8ba70d4fd7871e52"
    end
  end

  def install
    bin.install "uatu"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uatu --version")
  end
end
