# frozen_string_literal: true

# This file was generated by bin/update-formulae.
class Wpdiff < Formula
  desc "Diff locally installed WordPress plugins against their upstream versions"
  homepage "https://github.com/almeidx/wpdiff"
  version "0.1.1-alpha.1"
  license "Apache-2.0"

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/almeidx/wpdiff/releases/download/v0.1.1-alpha.1/wpdiff-0.1.1-alpha.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2c6bb1e589e85a69d311c571361f28eea0175f25869fae0024a742fa5ee348eb"
    end

    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/almeidx/wpdiff/releases/download/v0.1.1-alpha.1/wpdiff-0.1.1-alpha.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "17c36e870741c2e1eb9bb13d2a57faf07f1b031e597113fae0bf32f7f0ab8a4b"
    end
  end

  def install
    bin.install "wpdiff"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wpdiff --version")
  end
end
